### ISSUE TITLE
[1.20.1] Runaway memory allocation with Theurgy installed

### ISSUE THREAD

**Issue by MuteTiefling** [Buuz135/Replication#16] opened 2024-05-26 14:08 UTC
After installing Theurgy in a pack that already includes Replication, it seems that the Matter value calculation causes runaway memory allocation, causing the game to run out of memory within a few minutes and crash. I say it seems to be Matter calculation because the entire time leading up to the crash, the matter values still have not been fully synchronized. 

**Replication Version:**
1.20.1-1.0.3

**Titanium Version:**
1.20.1-3.8.28

**Crashlog If Applicable (Upload to pastebin/gist):**

Crash logs seem entirely unrelated but here it is just the same. https://gist.github.com/MuteTiefling/acd5ab4db5adf9119f48354ce7e18d03

**Comment by klikli-dev** [comment] 2024-05-26 14:11
Hi there, this is the Author of Theurgy!
@Buuz135 let me know if there is something I can do on my end! 
Without having looked at things, I assume you are somehow checking recipes to arrive at a value result?

**Comment by malcolmriley** [comment] 2024-06-06 20:02
Hello,

I've just encountered this issue as well, albeit in another context. I believe the issue is caused by the recipe analysis in Aequivaleo and have posted some preliminary findings [in this thread.](https://github.com/ldtteam/Aequivaleo/issues/26#issuecomment-2151404062) In short, it seems to be the result of the combinatorial explosion of recipe relationships that naturally arise in modpacks and not due to any particular mod.

Would it be possible for Replication to provide a "static" mode that does not rely on recipe graph analysis?

**Comment by MuteTiefling** [comment] 2024-06-06 21:00
Thanks for that writeup and insight Malcom.

**Comment by Buuz135** [comment] 2024-12-31 12:06
Fixed in 1.21

**Closed by Buuz135** 2024-12-31 12:06 UTC
